### ISSUE TITLE
Need help so i can start doing the assignment

### ISSUE THREAD

**Issue by Antonioescp** [jhu-ep-coursera/recipe_puppy_bootstrap#2]
Im not able to run rails s using this app, i get an error which says:

" require cannot load such file sqlite3/sqlite3_native " 

at the end.

I cannot start working on the assignment.

**Comment by Antonioescp** [comment]
output:

C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Traceback (most recent call last):
        17: from bin/rails:9:in `<main>'
        16: from bin/rails:9:in `require'
        15: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
        14: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        13: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:75:in `server'
        12: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
        11: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        10: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:78:in `require'
         9: from C:/repos/Coursera/RubyEsp/Course1/recipe_puppy_bootstrap/config/application.rb:7:in `<top (required)>'
         8: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler.rb:114:in `require'
         7: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
         6: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
         5: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
         4: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
         3: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
         2: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
         1: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:4:in `<top (required)>'
C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:4:in `require': cannot load such file -- sqlite3/2.6/sqlite3_native (LoadError)
        18: from bin/rails:9:in `<main>'
        17: from bin/rails:9:in `require'
        16: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
        15: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        14: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:75:in `server'
        13: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
        12: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        11: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:78:in `require'
        10: from C:/repos/Coursera/RubyEsp/Course1/recipe_puppy_bootstrap/config/application.rb:7:in `<top (required)>'
         9: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler.rb:114:in `require'
         8: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
         7: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
         6: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
         5: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
         4: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
         3: from C:/Ruby/Ruby26-x64/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
         2: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
         1: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:6:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)

**Comment by ychaikin** [comment]
@Antonioescp Did you miss the part where it said not to post questions here as issues on the repository but instead to use the course's forum?
